# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  perspeqtive_sulu_permission_aware_templates.admin.templates_admin:
    class: PERSPEQTIVE\SuluPermissionAwareTemplatesBundle\Admin\TemplatesAdmin
    arguments:
      $metadataProvider: '@sulu_admin.form_metadata_provider'
      $securityChecker: '@sulu_security.security_checker'
      $toolbarActionUpdater: '@perspeqtive_sulu_permission_aware_templates.toolbar_action.toolbar_action_updater'
    tags:
      - { name: sulu.admin }
      - { name: sulu.context, context: admin }

  perspeqtive_sulu_permission_aware_templates.toolbar_action.toolbar_action_updater:
    class: PERSPEQTIVE\SuluPermissionAwareTemplatesBundle\ToolbarAction\ToolbarActionUpdater


