services:
  perspeqtive_sulu_permission_aware_templates.admin.templates_admin:
    class: PERSPEQTIVE\SuluPermissionAwareTemplatesBundle\Admin\TemplatesAdmin
    arguments:
      $formMetadataLoader: '@sulu_admin.structure_form_metadata_loader'
      $securityChecker: '@sulu_security.security_checker'
    tags:
      - { name: sulu.admin }
      - { name: sulu.context, context: admin }


